### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by drbeat** [alephsecurity/initroot#1]
hi,

the credric is moto g5 and athene is moto g4 :)
you accidently wrote g6 and g5

regards

**Comment by roeeh** [comment]
Good catch!:)
Will be fixed next week as I am currently travelling.

Thanks

**Comment by drbeat** [comment]
Another thing:
I have a Moto G5 Plus and followed your blog post.
With 'fastboot oem config fsg-id "a androidboot.foo=bar"' I managed to create the property.

I did not follow further as I need the phone for business & private but I guess everything else should be straight forward.

**Comment by roeeh** [comment]
Good to hear :) I will soon make a list of all models that people have reported to be vulnerable

**Comment by wyjxiaoduo** [comment]
I have a G5 Plus, with 'fastboot oem config fsg-id "a androidboot.foo=bar"' I managed to create the property,  but unexpectedly , after 

fastboot oem config fsg-id "a initrd=0xA2100000,1601123"
fastboot flash foo ramdisk.cpio.gz
fastboot continue

the devices ran into infinite boot loops...

**Comment by drbeat** [comment]
which ramdisk did you use?

**Comment by wyjxiaoduo** [comment]
I got it from boot.img  in  POTTER_AMZ_NPN25.137-35_cid18_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip

**Comment by wyjxiaoduo** [comment]
Had anyone else  tested moto g5 plus？

**Comment by drbeat** [comment]
I heard the hole was fixed in the latest version. I did not try as I need the phone for business purposes.
But if you are able to run the command
fastboot oem config fsg-id "a androidboot.foo=bar

and get the desired output you should be able to run root if you have a modified initram.
you may use a different padding than in the readme as it was not tested

**Comment by Hitechcomputergeek** [comment]
EDIT: moved to [new issue](https://github.com/alephsecurity/initroot/issues/11)

**Comment by ghost** [comment]
@Hitechcomputergeek this is an issue unrelated to your problem. Not trying to be rude but, make another issue if you've got a problem.
