### ISSUE TITLE
Moto G4 Play XT1607 Persistent root proof

### ISSUE THREAD

**Issue by martinmullins** [alephsecurity/initroot#9]
Hey was able to get persistent root on the XT1607:
- Using the padC partition (8 MB total) ie. /dev/block/mmcblk0p34
- Using this ext4 [root partition](https://cdn.rawgit.com/m-mullins/InitRoot_Harpia/270c023f/initroot.ext4)

**Comment by roeeh** [comment]
Great job!:) Will update the README soon.

**Comment by moneymike8515** [comment]
Dose any one have any thing on the xt1609

**Comment by ghost** [comment]
@moneymike8515 go do some research. This issue is closed. Why not check the repo he linked.
